version: '3.8'

services:
  # bycoders.cnab.api:
  #   image: ${DOCKER_REGISTRY-}bycoderscnabapi
  #   build:
  #     context: .
  #     dockerfile: bycoders.cnab.api/Dockerfile
  #   depends_on: 
  #     - bycoders.database
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "5001:80"
 
  bycoders.cnab.web:
    extends:
      file: ./bycoders.cnab.webclient/docker-compose.yml
      service: web

  bycoders.database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment: 
      MYSQL_ROOT_PASSWORD: pass@root
      MYSQL_USER: newuser
      MYSQL_PASSWORD: pass@user
      MYSQL_DATABASE: coderbyte