version: '3.8'

services:
  bycoders.cnab.api:
    image: ${DOCKER_REGISTRY-}bycoderscnabapi
    build:
      context: .
      dockerfile: bycoders.cnab.api/Dockerfile
    depends_on: 
      - bycoders.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=host=bycoders.database;Port=5432;Database=Stackup;User Id=admin;Password=admin;
    ports:
      - "5001:80"    
 
  # bycoders.cnab.web:
  #   extends:
  #     file: ./bycoders.cnab.webclient/docker-compose.yml
  #     service: web  
  
  bycoders.database:
    image: postgres
    container_name: bycoders.database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stackup_postgress     